###Exercise on Functions:

1. Create a Python program that converts between different units of measurement.

In [2]:
def convert_length(value, unit_from, unit_to):
    """Converts between meters and feet.

    value (float): The value to be converted.
    unit_from (str): The unit to convert from ('m' or 'ft').
    unit_to (str): The unit to convert to ('m' or 'ft').

    Returns:
    float: The converted value.
    """
    if unit_from == 'm' and unit_to == 'ft':
        return value * 3.28084  # Convert meters to feet
    elif unit_from == 'ft' and unit_to == 'm':
        return value / 3.28084  # Convert feet to meters
    else:
        raise ValueError("Unsupported units for length conversion.")

def convert_weight(value, unit_from, unit_to):
    """Converts between kilograms and pounds.

    value (float): The value to be converted.
    unit_from (str): The unit to convert from ('kg' or 'lbs').
    unit_to (str): The unit to convert to ('kg' or 'lbs').

    Returns:
    float: The converted value.
    """
    if unit_from == 'kg' and unit_to == 'lbs':
        return value * 2.20462  # Convert kilograms to pounds
    elif unit_from == 'lbs' and unit_to == 'kg':
        return value / 2.20462  # Convert pounds to kilograms
    else:
        raise ValueError("Unsupported units for weight conversion.")

def convert_volume(value, unit_from, unit_to):
    """Converts between liters and gallons.

    value (float): The value to be converted.
    unit_from (str): The unit to convert from ('L' or 'gal').
    unit_to (str): The unit to convert to ('L' or 'gal').

    Returns:
    float: The converted value.
    """
    if unit_from == 'L' and unit_to == 'gal':
        return value * 0.264172  # Convert liters to gallons
    elif unit_from == 'gal' and unit_to == 'L':
        return value / 0.264172  # Convert gallons to liters
    else:
        raise ValueError("Unsupported units for volume conversion.")

def main():
    print("Welcome to the Unit Converter!")
    print("Choose the type of conversion:")
    print("1. Length (m to ft, ft to m)")
    print("2. Weight (kg to lbs, lbs to kg)")
    print("3. Volume (L to gal, gal to L)")

    try:
        choice = int(input("Enter the number corresponding to your choice: "))

        if choice not in [1, 2, 3]:
            raise ValueError("Invalid choice. Please choose 1, 2, or 3.")

        value = float(input("Enter the value to be converted: "))

        if choice == 1:
            unit_from = input("Enter the unit to convert from (m or ft): ").strip().lower()
            unit_to = input("Enter the unit to convert to (m or ft): ").strip().lower()
            result = convert_length(value, unit_from, unit_to)
            print(f"{value} {unit_from} is equal to {result} {unit_to}")

        elif choice == 2:
            unit_from = input("Enter the unit to convert from (kg or lbs): ").strip().lower()
            unit_to = input("Enter the unit to convert to (kg or lbs): ").strip().lower()
            result = convert_weight(value, unit_from, unit_to)
            print(f"{value} {unit_from} is equal to {result} {unit_to}")

        elif choice == 3:
            unit_from = input("Enter the unit to convert from (L or gal): ").strip().lower()
            unit_to = input("Enter the unit to convert to (L or gal): ").strip().lower()
            result = convert_volume(value, unit_from, unit_to)
            print(f"{value} {unit_from} is equal to {result} {unit_to}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Welcome to the Unit Converter!
Choose the type of conversion:
1. Length (m to ft, ft to m)
2. Weight (kg to lbs, lbs to kg)
3. Volume (L to gal, gal to L)
Enter the number corresponding to your choice: 2
Enter the value to be converted: 7
Enter the unit to convert from (kg or lbs): kg
Enter the unit to convert to (kg or lbs): lbs
7.0 kg is equal to 15.432339999999998 lbs


2. Create a Python program that performs various mathematical operations on a list of numbers.

In [3]:
def find_sum(numbers):
    """Calculates the sum of a list of numbers.

    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers in the list.
    """
    return sum(numbers)

def find_average(numbers):
    """Calculates the average of a list of numbers.

    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers in the list.
    """
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """Finds the maximum value in a list of numbers.

    numbers (list): A list of numeric values.

    Returns:
    float: The maximum value in the list.
    """
    return max(numbers)

def find_minimum(numbers):
    """Finds the minimum value in a list of numbers.

    numbers (list): A list of numeric values.

    Returns:
    float: The minimum value in the list.
    """
    return min(numbers)

def main():
    print("Welcome to the Mathematical Operations Program!")
    print("Choose the operation you want to perform:")
    print("1. Sum of numbers")
    print("2. Average of numbers")
    print("3. Maximum of numbers")
    print("4. Minimum of numbers")

    try:
        choice = int(input("Enter the number corresponding to your choice: "))

        if choice not in [1, 2, 3, 4]:
            raise ValueError("Invalid choice. Please select a valid option (1-4).")

        numbers_input = input("Enter a list of numbers separated by spaces: ")
        # Convert the input string to a list of numbers
        numbers = [float(num) for num in numbers_input.split()]

        if not numbers:
            raise ValueError("The list of numbers cannot be empty.")

        if choice == 1:
            result = find_sum(numbers)
            print(f"The sum of the numbers is: {result}")
        elif choice == 2:
            result = find_average(numbers)
            print(f"The average of the numbers is: {result}")
        elif choice == 3:
            result = find_maximum(numbers)
            print(f"The maximum value is: {result}")
        elif choice == 4:
            result = find_minimum(numbers)
            print(f"The minimum value is: {result}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Welcome to the Mathematical Operations Program!
Choose the operation you want to perform:
1. Sum of numbers
2. Average of numbers
3. Maximum of numbers
4. Minimum of numbers
Enter the number corresponding to your choice: 3
Enter a list of numbers separated by spaces: 29 10 33 11 2
The maximum value is: 33.0


###Exercise on List Manipulation:

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

In [4]:
def extract_every_other(lst):
    """Extracts every other element from the input list, starting from the first element.

    lst (list): A list of elements.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]  # This slices the list starting from index 0 and takes every second element

# Taking input from the user
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the input string to a list of integers
input_list = [int(item) for item in user_input.split()]

# Extract every other element from the list
output_list = extract_every_other(input_list)
print("The extracted list with every other element is:", output_list)


Enter a list of numbers separated by spaces: 3 8 9 1 2
The extracted list with every other element is: [3, 9, 2]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [1]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list, starting from index 'start' to 'end' (inclusive).

    :param lst: List from which to extract the sublist
    :param start: Starting index (inclusive)
    :param end: Ending index (inclusive)
    :return: Sublist from start to end
    """
    return lst[start:end+1]

lst = list(map(int, input("Enter the list elements separated by space: ").split()))
start = int(input("Enter the starting index: "))
end = int(input("Enter the ending index: "))
print("Sublist:", get_sublist(lst, start, end))


Enter the list elements separated by space: 3 6 12 11 13
Enter the starting index: 3
Enter the ending index: 4
Sublist: [11, 13]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

In [2]:
def reverse_list(lst):
    """Reverses a given list using slicing.

    lst (list): The list to be reversed.

    Returns:
    list: A new list that is the reverse of the original list.
    """
    return lst[::-1]  # Slicing with step -1 reverses the list


user_input = input("Enter a list of numbers separated by spaces: ")
# Convert the input string to a list of integers
input_list = [int(item) for item in user_input.split()]

# Reverse the list
output_list = reverse_list(input_list)
print("The reversed list is:", output_list)


Enter a list of numbers separated by spaces: 3 4 12 22 11 21
The reversed list is: [21, 11, 22, 12, 4, 3]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [3]:
def remove_first_last(lst):
    """Removes the first and last elements from a given list.

    lst (list): The original list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]  # Slicing from index 1 to second last index removes the first and last elements
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the input string to a list of integers
input_list = [int(item) for item in user_input.split()]
if len(input_list) < 2:
    print("The list must have at least two elements to remove the first and last ones.")
else:
    output_list = remove_first_last(input_list)
    print("The list after removing the first and last elements:", output_list)


Enter a list of numbers separated by spaces: 33 21 71 12 55
The list after removing the first and last elements: [21, 71, 12]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

In [4]:
def get_first_n(lst, n):
    """Extracts the first n elements from a given list.

    lst (list): The original list.
    n (int): The number of elements to extract.

    Returns:
    list: A new list containing the first n elements.
    """
    return lst[:n]  # Slicing from the start up to index n (exclusive)

user_input = input("Enter a list of numbers separated by spaces: ")
n = int(input("Enter the number of elements to extract: "))

# Convert the input string to a list of integers
input_list = [int(item) for item in user_input.split()]

# Check if n is within valid range
if n < 0:
    print("Please enter a positive number for n.")
elif n > len(input_list):
    print("n is larger than the list size. Returning the whole list:", input_list)
else:
    # Get the first n elements
    output_list = get_first_n(input_list, n)
    print(f"The first {n} elements are:", output_list)


Enter a list of numbers separated by spaces: 33 21 11 24 55 76 7
Enter the number of elements to extract: 3
The first 3 elements are: [33, 21, 11]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [5]:
def get_last_n(lst, n):
    """Extracts the last n elements from a given list.

    lst (list): The original list.
    n (int): The number of elements to extract from the end.

    Returns:
    list: A new list containing the last n elements.
    """
    return lst[-n:]  # Slicing from the last n elements

user_input = input("Enter a list of numbers separated by spaces: ")
n = int(input("Enter the number of elements to extract from the end: "))

# Convert the input string to a list of integers
input_list = [int(item) for item in user_input.split()]

# Check if n is within valid range
if n < 0:
    print("Please enter a positive number for n.")
elif n > len(input_list):
    print("n is larger than the list size. Returning the whole list:", input_list)
else:
    # Get the last n elements
    output_list = get_last_n(input_list, n)
    print(f"The last {n} elements are:", output_list)


Enter a list of numbers separated by spaces: 32 22 1 2 32 1 5 
Enter the number of elements to extract from the end: 5
The last 5 elements are: [1, 2, 32, 1, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [7]:
def reverse_skip(lst):
    """Extracts every second element in reverse order, starting from the second-to-last element.

    lst (list): The original list.

    Returns:
    list: A new list containing every second element in reverse order.
    """
    return lst[-2::-2]  # Start from second-to-last, move backward skipping one element
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the input string to a list of integers
input_list = [int(item) for item in user_input.split()]

# Get the transformed list
output_list = reverse_skip(input_list)
print("In reverse order (skipping one):", output_list)


Enter a list of numbers separated by spaces: 22 32 12 1 4 5 21 77 8
In reverse order (skipping one): [77, 5, 1, 32]


###Exercise on Nested List:

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [8]:
def flatten(lst):
    """Flattens a nested list into a single list.
    lst (list): A nested list containing sublists.

    Returns:
    list: A flattened list with all elements in a single dimension.
    """
    flat_list = []  # Initialize an empty list
    for sublist in lst:
        flat_list.extend(sublist)  # Extend the flat_list with elements from sublists
    return flat_list
user_input = input("Enter a nested list (e.g., [[1,2], [3,4]]): ")

# Convert the user input into a nested list safely using eval
try:
    nested_list = eval(user_input)  # Convert string input to a list
    if isinstance(nested_list, list):  # Ensure it's a valid list
        output_list = flatten(nested_list)
        print("Flattened list:", output_list)
    else:
        print("Invalid input! Please enter a nested list.")
except:
    print("Invalid input! Please enter a valid nested list format.")


Enter a nested list (e.g., [[1,2], [3,4]]): [[3,2], [5], [6,7]]
Flattened list: [3, 2, 5, 6, 7]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

In [11]:
def access_nested_element(lst, indices):
    """Extracts a specific element from a nested list given its indices.

    lst (list): The nested list from which the element is to be accessed.
    indices (list): A list of indices specifying the position of the element.

    Returns:
    element: The element located at the specified indices in the nested list.
    """
    element = lst
    for index in indices:
        element = element[index]  # Navigate through the list using the indices
    return element

# Taking user input for the nested list
user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4]]): ")

# Convert the input string into a list using eval
try:
    nested_list = eval(user_input)  # Convert string input to a list
    if isinstance(nested_list, list):
        # Taking input for the list of indices
        indices_input = input("Enter a list of indices (e.g., [0, 1]): ")
        indices = [int(i) for i in indices_input.strip('[]').split(',')]

        # Call the function to extract the element
        output_element = access_nested_element(nested_list, indices)
        print(f"The element at the specified indices {indices} is:", output_element)
    else:
        print("The input is not a valid nested list.")
except Exception as e:
    print("Invalid input! Please ensure the format is correct.")
    print("Error:", e)


Enter a nested list (e.g., [[1, 2], [3, 4]]): [[3,2], [5], [6,7]]
Enter a list of indices (e.g., [0, 1]): [0,1]
The element at the specified indices [0, 1] is: 2


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [13]:
def sum_nested(lst):
    """Calculates the sum of all elements in a nested list, regardless of depth.

    lst (list): The nested list.

    Returns:
    int: The sum of all elements in the list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, recursively sum it
            total += sum_nested(item)
        else:
            total += item  # If it's a number, add it to the total
    return total
user_input = input("Enter a nested list (e.g., [[1, 2], [3, [4, 5]], 6]): ")
try:
    nested_list = eval(user_input)  # Convert string input to a list
    if isinstance(nested_list, list):
        # Call the function to sum the elements
        result = sum_nested(nested_list)
        print(f"The sum of all elements in the nested list is: {result}")
    else:
        print("The input is not a valid nested list.")
except Exception as e:
    print("Invalid input! Please ensure the format is correct.")
    print("Error:", e)


Enter a nested list (e.g., [[1, 2], [3, [4, 5]], 6]): [[9, 2], [4, [2, 5]], 8]
The sum of all elements in the nested list is: 30


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

In [15]:
def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list.

    lst (list): The nested list from which the element is to be removed.
    elem (any): The element to remove.

    Returns:
    list: A new list with all occurrences of elem removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, recursively remove the element
            result.append(remove_element(item, elem))
        else:
            if item != elem:  # Only add the item if it is not equal to elem
                result.append(item)
    return result

user_input = input("Enter a nested list: ")
elem = input("Enter the element to remove: ")

try:
    # Convert the input string into a list using eval
    nested_list = eval(user_input)
    # Convert elem to its appropriate type (for example, integer or string)
    elem = eval(elem)

    if isinstance(nested_list, list):
        # Call the function to remove the element
        modified_list = remove_element(nested_list, elem)
        print(f"The modified list after removing {elem} is:", modified_list)
    else:
        print("The input is not a valid nested list.")
except Exception as e:
    print("Invalid input! Please ensure the format is correct.")
    print("Error:", e)


Enter a nested list: [[9, 2], [4, [2, 5]], 8]
Enter the element to remove: 2
The modified list after removing 2 is: [[9], [4, [5]], 8]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [17]:
def find_max(lst):
    """Finds the maximum element in a nested list, regardless of depth.

    lst (list): The nested list from which to find the maximum element.

    Returns:
    int: The maximum element in the list.
    """
    max_value = float('-inf')  # Initialize max_value to negative infinity
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, recursively find the max
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)  # Compare the current item with max_value
    return max_value
user_input = input("Enter a nested list: ")
# Convert the input string into a list using eval
try:
    nested_list = eval(user_input)  # Convert string input to a list
    if isinstance(nested_list, list):
        # Call the function to find the maximum element
        result = find_max(nested_list)
        print(f"The maximum element in the nested list is: {result}")
    else:
        print("The input is not a valid nested list.")
except Exception as e:
    print("Invalid input! Please ensure the format is correct.")
    print("Error:", e)


Enter a nested list: [[9, 2], [4, [2, 5]], 8]
The maximum element in the nested list is: 9


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

In [19]:
def count_occurrences(lst, elem):
    """Counts how many times a specific element appears in a nested list.

    lst (list): The nested list to search through.
    elem (any): The element whose occurrences we want to count.

    Returns:
    int: The count of occurrences of elem in the list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, recursively count occurrences
            count += count_occurrences(item, elem)
        else:
            if item == elem:  # If the item matches the element, increase the count
                count += 1
    return count
user_input = input("Enter a nested list: ")
elem = input("Enter the element to count: ")

try:
    # Convert the input string into a list using eval
    nested_list = eval(user_input)
    # Convert elem to its appropriate type (e.g., integer or string)
    elem = eval(elem)
    if isinstance(nested_list, list):
        # Call the function to count occurrences
        occurrences = count_occurrences(nested_list, elem)
        print(f"The element {elem} appears {occurrences} times in the nested list.")
    else:
        print("The input is not a valid nested list.")
except Exception as e:
    print("Invalid input! Please ensure the format is correct.")
    print("Error:", e)


Enter a nested list: [[9, 2], [4, [2, 5]], 8]
Enter the element to count: 2
The element 2 appears 2 times in the nested list.


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [22]:
def deep_flatten(lst):
    """Flattens a deeply nested list into a single list, regardless of depth.

    Args:
    lst (list): The nested list to flatten.

    Returns:
    list: A flattened version of the nested list.
    """
    flattened_list = []
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recursively flatten it
            flattened_list.extend(deep_flatten(item))
        else:
            flattened_list.append(item)  # If it's not a list, add it to the result
    return flattened_list
user_input = input("Enter a nested list: ")
try:
    # Convert the input string into a list using eval
    nested_list = eval(user_input)

    if isinstance(nested_list, list):
        # Call the function to flatten the list
        flattened = deep_flatten(nested_list)
        print(f"The flattened list is: {flattened}")
    else:
        print("The input is not a valid list.")
except Exception as e:
    print("Invalid input! Please ensure the format is correct.")
    print("Error:", e)


Enter a nested list: [[[2, 5], [3, 9]], [[11, 6], [7, 6]]]
The flattened list is: [2, 5, 3, 9, 11, 6, 7, 6]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

In [24]:
def average_nested(lst):
    """Calculates the average of all elements in a nested list, regardless of depth.

    lst (list): The nested list whose elements' average is to be calculated.

    Returns:
    float: The average of all the elements in the list.
    """
    # Flatten the list
    def flatten(lst):
        flattened_list = []
        for item in lst:
            if isinstance(item, list):  # If the item is a list, recursively flatten it
                flattened_list.extend(flatten(item))
            else:
                flattened_list.append(item)  # If it's not a list, add it to the result
        return flattened_list

    # Flatten the nested list
    flattened_lst = flatten(lst)

    # Calculate the average
    if len(flattened_lst) == 0:
        return 0  # Avoid division by zero if the list is empty
    return sum(flattened_lst) / len(flattened_lst)
user_input = input("Enter a nested list:")
try:
    # Convert the input string into a list using eval
    nested_list = eval(user_input)

    if isinstance(nested_list, list):
        # Call the function to calculate the average
        average = average_nested(nested_list)
        print(f"The average of all elements in the nested list is: {average}")
    else:
        print("The input is not a valid nested list.")
except Exception as e:
    print("Invalid input! Please ensure the format is correct.")
    print("Error:", e)


Enter a nested list:[[[2, 5], [3, 9]], [[11, 6], [7, 6]]]
The average of all elements in the nested list is: 6.125


###Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [25]:
import numpy as np

In [46]:
# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):")
print(empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All Ones Array (4x2):")
print(ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 7)
print("\n3. Filled Array (3x3 filled with 7):")
print(fill_value_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("\n4. Zeros Like Array:")
print(zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\n5. Ones Like Array:")
print(ones_like_array)

# 6. For an existing list new_list = [1, 2, 3, 4], convert to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array_from_list = np.array(new_list)
print("\n6. Converted List to NumPy Array:")
print(numpy_array_from_list)

1. Empty Array (2x2):
[[2.5e-323 1.5e-323]
 [9.9e-324 4.9e-324]]

2. All Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Filled Array (3x3 filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Like Array:
[[0 0]
 [0 0]]

5. Ones Like Array:
[[1 1]
 [1 1]]

6. Converted List to NumPy Array:
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [27]:
# 1. Create an array with values ranging from 10 to 49
array_1 = np.arange(10, 50)
print("1. Array ranging from 10 to 49:")
print(array_1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix ranging from 0 to 8:")
print(matrix_2)

# 3. Create a 3x3 identity matrix
identity_matrix_3 = np.eye(3)
print("\n3. 3x3 Identity Matrix:")
print(identity_matrix_3)

# 4. Create a random array of size 30 and find the mean of the array
random_array_4 = np.random.random(30)
mean_random_array_4 = random_array_4.mean()
print("\n4. Random array of size 30 and its mean:")
print(random_array_4)
print(f"Mean of the random array: {mean_random_array_4}")

# 5. Create a 10x10 array with random values and find the minimum and maximum values
random_array_5 = np.random.random((10, 10))
min_value_5 = random_array_5.min()
max_value_5 = random_array_5.max()
print("\n5. 10x10 random array and its minimum and maximum values:")
print(random_array_5)
print(f"Minimum value: {min_value_5}")
print(f"Maximum value: {max_value_5}")

# 6. Create a zero array of size 10 and replace the 5th element with 1
array_6 = np.zeros(10)
array_6[4] = 1  # 5th element (index 4) is set to 1
print("\n6. Zero array of size 10 with the 5th element replaced by 1:")
print(array_6)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr_7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr_7 = arr_7[::-1]
print("\n7. Reversed array:")
print(reversed_arr_7)

# 8. Create a 2D array with 1 on the border and 0 inside
array_8 = np.ones((5, 5))
array_8[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:")
print(array_8)

# 9. Create a 8x8 matrix and fill it with a checkerboard pattern
checkerboard_9 = np.zeros((8, 8))
checkerboard_9[1::2, ::2] = 1
checkerboard_9[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:")
print(checkerboard_9)


1. Array ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30 and its mean:
[0.06676967 0.30027522 0.39421036 0.72778336 0.27370539 0.63857815
 0.62906312 0.90953802 0.97037125 0.7259826  0.70268398 0.9262288
 0.85367039 0.37050185 0.98562412 0.60392756 0.72684822 0.65954589
 0.18260706 0.75659268 0.11429787 0.11617899 0.34794443 0.31931667
 0.34554146 0.02071356 0.69554209 0.21456691 0.27016783 0.48676054]
Mean of the random array: 0.5111846013947706

5. 10x10 random array and its minimum and maximum values:
[[0.48049222 0.16853155 0.10603148 0.96152705 0.18466225 0.67812205
  0.71665871 0.84853942 0.13998437 0.94317844]
 [0.00895155 0.32298359 0.91967559 0.64670242 0.91773338 0.76061406
  0.17847421 0.33243802 0.02351542 0.149921  ]
 [0.1784

Problem - 3: Array Operations:

In [28]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = x + y
print("1. Add the two arrays (x + y):")
print(add_result)

# 2. Subtract the two arrays
subtract_result = x - y
print("\n2. Subtract the two arrays (x - y):")
print(subtract_result)

# 3. Multiply the array with any integers of your choice
# Here, we multiply `x` by 2 and `y` by 3
multiply_x = x * 2
multiply_y = y * 3
print("\n3. Multiply x by 2 and y by 3:")
print("x multiplied by 2:")
print(multiply_x)
print("y multiplied by 3:")
print(multiply_y)

# 4. Find the square of each element of the array
square_x = np.square(x)
square_y = np.square(y)
print("\n4. Square of each element of the arrays x and y:")
print("x squared:")
print(square_x)
print("y squared:")
print(square_y)

# 5. Find the dot product between:
# v and w; x and v; x and y

dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("\n5. Dot product results:")
print(f"Dot product between v and w: {dot_v_w}")
print(f"Dot product between x and v: {dot_x_v}")
print(f"Dot product between x and y: {dot_x_y}")

# 6. Concatenate x and y along rows (axis=0) and concatenate v and w along columns (axis=1)

concat_x_y = np.concatenate((x, y), axis=0)  # Along rows
concat_v_w = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # Along columns

print("\n6. Concatenated arrays:")
print(f"Concatenation of x and y along rows:")
print(concat_x_y)
print(f"Concatenation of v and w along columns:")
print(concat_v_w)

1. Add the two arrays (x + y):
[[ 6  8]
 [10 13]]

2. Subtract the two arrays (x - y):
[[-4 -4]
 [-4 -3]]

3. Multiply x by 2 and y by 3:
x multiplied by 2:
[[ 2  4]
 [ 6 10]]
y multiplied by 3:
[[15 18]
 [21 24]]

4. Square of each element of the arrays x and y:
x squared:
[[ 1  4]
 [ 9 25]]
y squared:
[[25 36]
 [49 64]]

5. Dot product results:
Dot product between v and w: 219
Dot product between x and v: [29 77]
Dot product between x and y: [[19 22]
 [50 58]]

6. Concatenated arrays:
Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
[[ 9 11]
 [10 12]]


In [29]:
# 7. Concatenate x and v
concat_x_v = np.concatenate((x, v), axis=0)
print("\n7. Concatenation of x and v:")
print(concat_x_v)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The error happened because x is a 2D array (2x2 matrix) and v is a 1D array, and numpy requires the number of columns (shape[1]) to be the same for both arrays when concatenating along rows (axis=0)

Problem - 4: Matrix Operations:

In [30]:
#1. Prove A.A^−1 = I.
# Define matrix A
A = np.array([[3, 4], [7, 8]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Compute A * A_inv
result_1 = np.dot(A, A_inv)

# Print the result
print("1. A * A^-1 = I:")
print(result_1)

# Verify if result is an identity matrix (I)
I = np.eye(2)  # Identity matrix of size 2x2
print("\nIdentity matrix I:")
print(I)

1. A * A^-1 = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix I:
[[1. 0.]
 [0. 1.]]


In [33]:
#2. Prove AB ̸= BA.
# Define matrix B
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\n2. AB and BA:")
print("AB:")
print(AB)
print("BA:")
print(BA)

print("\nIs AB equal to BA?", np.array_equal(AB, BA))


2. AB and BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]

Is AB equal to BA? False


In [32]:
#3. Prove (AB)^T = B^T A^T
# Compute (AB)^T
AB_T = np.transpose(AB)

# Compute B^T * A^T
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

print("\n3. (AB)^T = B^T * A^T:")
print("(AB)^T:")
print(AB_T)
print("B^T * A^T:")
print(B_T_A_T)

print("\nIs (AB)^T equal to B^T * A^T?", np.array_equal(AB_T, B_T_A_T))


3. (AB)^T = B^T * A^T:
(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T? True


In [34]:
#Solve the following system of Linear equation using Inverse Methods.

# Coefficient matrix A
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

# Result matrix B
B = np.array([-1, -3, 9])

# Solve for X using the inverse method
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("\nSolution for the linear system of equations:")
print("x =", X[0], ", y =", X[1], ", z =", X[2])


Solution for the linear system of equations:
x = 2.0 , y = 1.0 , z = -2.0


In [35]:
# Solve using np.linalg.solve
X_alt = np.linalg.solve(A, B)

print("\nSolution using np.linalg.solve:")
print("x =", X_alt[0], ", y =", X_alt[1], ", z =", X_alt[2])


Solution using np.linalg.solve:
x = 2.0 , y = 1.0000000000000002 , z = -2.0


1. Element-wise Addition:

In [36]:
import time
import numpy as np

# Create two lists of size 1,000,000 with random numbers for element-wise addition
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1, 1000001)]

# Measure the time taken for element-wise addition using Python lists
start_time = time.time()

result_list = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()
print("Time taken using Python lists: {:.6f} seconds".format(end_time - start_time))

Time taken using Python lists: 0.098719 seconds


In [37]:
# Create two numpy arrays of size 1,000,000
array1 = np.arange(1, 1000001)
array2 = np.arange(1, 1000001)

# Measure the time taken for element-wise addition using NumPy arrays
start_time = time.time()

result_array = array1 + array2

end_time = time.time()
print("Time taken using NumPy arrays: {:.6f} seconds".format(end_time - start_time))


Time taken using NumPy arrays: 0.013148 seconds


2. Element-wise Multiplication

In [38]:
# Create two lists of size 1,000,000 with random numbers for element-wise multiplication
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1, 1000001)]

# Measure the time taken for element-wise multiplication using Python lists
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()
print("Time taken using Python lists: {:.6f} seconds".format(end_time - start_time))

Time taken using Python lists: 0.118862 seconds


In [39]:
# Create two numpy arrays of size 1,000,000
array1 = np.arange(1, 1000001)
array2 = np.arange(1, 1000001)

# Measure the time taken for element-wise multiplication using NumPy arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print("Time taken using NumPy arrays: {:.6f} seconds".format(end_time - start_time))


Time taken using NumPy arrays: 0.004797 seconds


3. Dot Product

In [40]:
# Create two lists of size 1,000,000 with random numbers for dot product calculation
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1, 1000001)]

# Measure the time taken for dot product using Python lists
start_time = time.time()

# Compute dot product using Python lists
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()
print("Time taken using Python lists: {:.6f} seconds".format(end_time - start_time))

Time taken using Python lists: 0.135771 seconds


In [41]:
# Create two numpy arrays of size 1,000,000
array1 = np.arange(1, 1000001)
array2 = np.arange(1, 1000001)

# Measure the time taken for dot product using NumPy arrays
start_time = time.time()
# Compute dot product using NumPy arrays
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print("Time taken using NumPy arrays: {:.6f} seconds".format(end_time - start_time))


Time taken using NumPy arrays: 0.002422 seconds


4. Matrix Multiplication

In [44]:
# Create two 1000x1000 matrices using Python lists
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]

# Matrix multiplication using Python lists
start_time = time.time()
result_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()
print("Time taken using Python lists:", end_time - start_time, "seconds")

Time taken using Python lists: 198.30599761009216 seconds


In [45]:
# Create the same 1000x1000 matrices using NumPy arrays
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

# Matrix multiplication using NumPy arrays
start_time = time.time()
result_numpy = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
print("Time taken using Numpy arrays:", end_time - start_time, "seconds")

Time taken using Numpy arrays: 3.0050179958343506 seconds
